Vagrant.configure(2) do |config|
  config.vm.box = "centos67"
	config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.7-x86_64-v20151108.box"
	config.vm.network "public_network", ip: "192.168.1.120"
  config.vm.synced_folder "../../project", "/vagrant_data",
    :owner => "vagrant",
    :group => "vagrant",
    :mount_options => ["dmode=777,fmode=777"]
  config.vm.provider "virtualbox" do |vb|
		vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "2", "--ioapic", "on"]
  end
  Encoding.default_external = 'UTF-8'
end
